package com.vibethroughcode.ftree.nearby.wire

import java.io.File
import java.math.BigInteger
import org.junit.Assert.assertEquals
import org.junit.Test

/**
 * Everything the Kotlin and the JavaScript have to agree about, written down.
 *
 * This is not a test of what the answers *should* be — the other files in this package are that.
 * It is a record of what they *are*, so that the desktop implementation has something to be right
 * against, and so that a change to any of it has to show its work: the diff on `vectors.txt` is
 * the list of things that moved, and a pull request that moves one without meaning to is visible
 * at a glance rather than discovered by two people holding two phones.
 *
 * It exists because nearby sharing is built twice. `docs/desktop.md` already names the cost of
 * that arrangement — *"a second implementation of the app's behaviour, in a second language, kept
 * in step by hand"* — and for the `.ftree` format, by hand is enough: a field read wrongly shows up
 * as a wrong name on a screen and somebody says so. A handshake is different. Two implementations
 * that disagree by one byte derive different keys and show two different six-digit codes, and the
 * people holding the devices correctly conclude that something is wrong and incorrectly conclude
 * what: the failure is indistinguishable from the attack the codes exist to detect.
 *
 * So the agreement is a file rather than an intention. `desktop/nearby/vectors.test.js` reads this
 * same table.
 *
 * The groups that carry the weight:
 *
 *   to256      the padding trap. `BigInteger.toByteArray()` prepends a sign byte when bit 2047 is
 *              set; Node's `computeSecret()` strips leading zeros. A shared secret beginning 0x00
 *              is 255 bytes there and 256 here, one time in 256, and unpadded the two sides agree
 *              a secret and then derive different keys from it.
 *
 *   handshake  a whole scripted exchange with fixed keys and fixed nonces, down to the six digits.
 *              If both languages produce this table, they interoperate. If they produce anything
 *              else, they do not, whatever the rest of the suite says.
 *
 *   nonce      includes sequence 2^53, which is where a JavaScript Number stops being exact. That
 *              line fails the moment the desktop side stops using BigInt, and passes every smaller
 *              case until then.
 *
 * Regenerate deliberately, never casually:
 *   UPDATE_GOLDEN=1 ./gradlew testDebugUnitTest --tests '*NearbyVectorsTest'
 * The regenerated file is the deliverable of the pull request that moves it, and it should be read.
 */
class NearbyVectorsTest {

    @Test
    fun `the vectors are what they have always been`() {
        val produced = buildVectors()
        val file = vectorsFile()

        if (System.getenv("UPDATE_GOLDEN") == "1") {
            file.parentFile?.mkdirs()
            file.writeText(produced)
            return
        }

        if (!file.exists()) {
            throw AssertionError(
                "${file.path} is missing. Generate it with " +
                    "UPDATE_GOLDEN=1 ./gradlew testDebugUnitTest --tests '*NearbyVectorsTest'",
            )
        }

        // Compared line by line so the failure names the line that moved rather than printing two
        // thousand characters of hex and leaving the reader to diff them by eye.
        val expected = file.readText().replace("\r\n", "\n").lines()
        val actual = produced.lines()
        val moved = expected.indices
            .filter { it < actual.size && expected[it] != actual[it] }
            .take(5)

        if (moved.isNotEmpty() || expected.size != actual.size) {
            val detail = moved.joinToString("\n") { index ->
                "  line ${index + 1}\n    was: ${expected[index]}\n    now: ${actual[index]}"
            }
            throw AssertionError(
                "the nearby vectors moved (${expected.size} lines expected, ${actual.size} now)\n" +
                    detail +
                    "\n\nIf this is deliberate, regenerate and read the diff.",
            )
        }
        assertEquals(expected, actual)
    }

    // ------------------------------------------------------------------------------------------

    private fun buildVectors(): String = buildString {
        appendLine("# Every value the two nearby implementations have to agree on.")
        appendLine("# Generated by NearbyVectorsTest. Regenerate with UPDATE_GOLDEN=1, and read the diff.")
        appendLine("#")
        appendLine("# Format: <group> | <input> | <output>. Bytes are lowercase hex.")
        appendLine("# Read by app/src/test/.../NearbyVectorsTest.kt and desktop/nearby/vectors.test.js.")
        appendLine()

        section("to256")
        // The four shapes that differ between the two languages' big-number libraries.
        for ((label, value) in listOf(
            "two" to BigInteger.valueOf(2),
            "leading-zero-byte" to BigInteger.ONE.shiftLeft(2039),
            "top-bit-set" to BigInteger.ONE.shiftLeft(2047),
            "full-width" to Dh.P.subtract(BigInteger.TWO),
        )) {
            line("to256", label, Dh.to256(value).hex())
        }
        appendLine()

        section("dh")
        for (exponent in listOf(2L, 3L, 0xC0FFEEL)) {
            val private = BigInteger.valueOf(exponent)
            line("dh.public", "x=$exponent", Dh.to256(Dh.publicOf(private)).hex())
        }
        run {
            val a = BigInteger.valueOf(0xA11CEL)
            val b = BigInteger.valueOf(0xB0BL)
            val shared = Dh.sharedSecret(a, Dh.publicOf(b))
            line("dh.shared", "a=0xa11ce b=0xb0b", Dh.to256(shared).hex())
        }
        appendLine()

        section("hkdf")
        run {
            val prk = ByteArray(32) { (it + 1).toByte() }
            for (label in listOf(
                NearbyProtocol.LABEL_SENDER_TO_RECEIVER,
                NearbyProtocol.LABEL_RECEIVER_TO_SENDER,
                NearbyProtocol.LABEL_SAS,
            )) {
                val length = if (label == NearbyProtocol.LABEL_SAS) 8 else 32
                line("hkdf", "prk=01..20 label=$label len=$length", Handshake.expand(prk, label, length).hex())
            }
        }
        appendLine()

        section("handshake")
        // One scripted exchange, entirely deterministic. This is the vector: if both languages
        // produce these four values, they can talk to each other.
        for (paired in listOf(false, true)) {
            val transcript = TranscriptHash()
                .add(encodeFrame(NearbyProtocol.TYPE_HELLO, ByteArray(29) { 1 }))
                .add(encodeFrame(NearbyProtocol.TYPE_HELLO_ACK, ByteArray(29) { 2 }))
                .add(encodeFrame(NearbyProtocol.TYPE_KEY, ByteArray(288) { 3 }))
                .add(encodeFrame(NearbyProtocol.TYPE_KEY_ACK, ByteArray(288) { 4 }))
                .value()
            val token = if (paired) ByteArray(16) { (it + 0x40).toByte() } else Handshake.NO_TOKEN
            val shared = Dh.sharedSecret(BigInteger.valueOf(0xA11CEL), Dh.publicOf(BigInteger.valueOf(0xB0BL)))
            val prk = Handshake.extract(transcript, token, shared)
            val keys = Handshake.deriveKeys(prk)
            val which = if (paired) "with-token" else "no-token"

            line("handshake.transcript", which, transcript.hex())
            line("handshake.prk", which, prk.hex())
            line("handshake.s2r", which, keys.senderToReceiver.hex())
            line("handshake.r2s", which, keys.receiverToSender.hex())
            line("handshake.sas", which, keys.sas)
        }
        appendLine()

        section("sas")
        for ((label, raw) in listOf(
            "zero" to ByteArray(8),
            "seven" to ByteArray(8).also { it[7] = 7 },
            "all-ones" to ByteArray(8) { 0xFF.toByte() },
            "high-bit" to ByteArray(8).also { it[0] = 0x80.toByte() },
        )) {
            line("sas", label, Handshake.sasDigits(raw))
        }
        appendLine()

        section("nonce")
        for (direction in listOf(
            NearbyProtocol.DIRECTION_SENDER_TO_RECEIVER,
            NearbyProtocol.DIRECTION_RECEIVER_TO_SENDER,
        )) {
            for (sequence in listOf(0L, 1L, 0xFFFFFFFFL, 1L shl 32, 1L shl 53, -1L)) {
                val shown = if (sequence == -1L) "18446744073709551615" else sequence.toString()
                line("nonce", "dir=$direction seq=$shown", FrameCrypto.nonceFor(direction, sequence).hex())
            }
        }
        appendLine()

        section("gcm")
        run {
            val key = ByteArray(32) { (it + 1).toByte() }
            for ((label, plaintext) in listOf(
                "empty" to ByteArray(0),
                "short" to "a family".toByteArray(),
                "block" to ByteArray(64) { (it * 3).toByte() },
            )) {
                val sealed = FrameCrypto.seal(key, 1, 0, NearbyProtocol.TYPE_DATA, plaintext)
                line("gcm", "key=01..20 dir=1 seq=0 type=0x20 pt=$label", sealed.hex())
            }
        }
        appendLine()

        section("frame")
        for ((label, payload) in listOf(
            "empty" to ByteArray(0),
            "one" to byteArrayOf(0x41),
            "sixteen" to ByteArray(16) { it.toByte() },
        )) {
            line("frame", "type=0x10 payload=$label", encodeFrame(NearbyProtocol.TYPE_OFFER, payload).hex())
        }
        appendLine()

        section("beacon")
        run {
            val deviceId = DeviceId(ByteArray(16) { (it + 1).toByte() })
            val fingerprint = ByteArray(8) { (it * 3).toByte() }
            for ((label, name) in listOf(
                "ascii" to "Quiet Heron",
                "devanagari" to "अंकित",
                "longest" to "n".repeat(80),
            )) {
                val beacon = Beacon.announce(
                    platform = NearbyPlatform.ANDROID,
                    flags = NearbyProtocol.FLAG_ACCEPTS_TREE,
                    tcpPort = 49813,
                    deviceId = deviceId,
                    keyFingerprint = fingerprint,
                    displayName = name,
                )
                line("beacon", "name=$label", beacon.encode().hex())
            }
            line("beacon", "query", Beacon.query().encode().hex())
        }
        appendLine()

        section("names")
        for (pair in listOf(0 to 0, 1 to 2, 0xFF to 0x80, 0x7F to 0x10)) {
            val id = ByteArray(16).also { it[0] = pair.first.toByte(); it[1] = pair.second.toByte() }
            line("names", "id=%02x%02x".format(pair.first, pair.second), NearbyNames.friendlyName(id))
        }
        appendLine()

        section("problems")
        for (problem in NearbyProblem.entries) {
            line("problems", problem.name, "0x%02x".format(problem.code))
        }
        appendLine()

        section("import-problems")
        for (problem in com.vibethroughcode.ftree.transfer.ImportProblem.entries) {
            line("import-problems", problem.name, "0x%02x".format(ImportProblemCodes.codeOf(problem)))
        }
        appendLine()

        section("qrlink")
        run {
            val link = QrLink(
                address = "192.168.1.42",
                port = 49813,
                deviceId = DeviceId(ByteArray(16) { (it * 7).toByte() }),
                keyFingerprint = ByteArray(8) { (it + 1).toByte() },
                token = ByteArray(16) { (it * 11).toByte() },
                displayName = "Quiet Heron",
            )
            line("qrlink", "encode", link.encode())
        }
        for (address in listOf("10.0.0.1", "172.16.0.1", "192.168.1.1", "169.254.1.1", "8.8.8.8", "172.32.0.1", "10.0.0.010")) {
            line("qrlink.private", address, QrLink.isPrivateAddress(address).toString())
        }
    }

    private fun StringBuilder.section(name: String) {
        appendLine("# --- $name ---")
    }

    private fun StringBuilder.line(group: String, input: String, output: String) {
        appendLine("$group | $input | $output")
    }

    private fun ByteArray.hex(): String = joinToString("") { "%02x".format(it) }

    /**
     * Walks up from the working directory until it finds the repository root.
     *
     * Gradle runs a unit test with `user.dir` at the module, an IDE sometimes at the project, and
     * neither is a thing to hard-code. Looking for `settings.gradle.kts` works from both.
     */
    private fun vectorsFile(): File {
        var directory: File? = File(System.getProperty("user.dir"))
        while (directory != null && !File(directory, "settings.gradle.kts").exists()) {
            directory = directory.parentFile
        }
        val root = directory ?: error("could not find the repository root from ${System.getProperty("user.dir")}")
        return File(root, "docs/nearby/vectors.txt")
    }
}
